spring:
  application:
    name: DagobahLab

  datasource:
    url: jdbc:mysql://localhost:13306/dagobah_lab?serverTimezone=UTC&characterEncoding=UTF-8
    username: master
    password: yoda
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: none # DB ??? ?? (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # ?? ?? ?? (??)
        show_sql: true       # ?? ?? ??

  jackson:
    visibility:
      field: none
      setter: public_only